### GET top stories
GET https://hacker-news.firebaseio.com/v0/topstories.json

### GET item
@id = 41361281
GET https://hacker-news.firebaseio.com/v0/item/{{id}}.json

### GET comments
@comment_id = 41363714
GET https://hacker-news.firebaseio.com/v0/item/{{comment_id}}.json

### GET user
@user_id = epistasis
GET https://hacker-news.firebaseio.com/v0/user/{{user_id}}.json
